logging:
  level:
    com.example.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%X{uuid}){yellow} %clr(%X{userId}){yellow} %clr(%-40.40logger){cyan} %clr(:){faint} %msg%n"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imhero
    username: tkang
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always